name: practice_flame
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flame:
    path: packages/flame/packages/flame
  flame_tiled:
    path: packages/flame/packages/flame_tiled
  flame_audio:
    path: packages/flame/packages/flame_audio
#  flame: ^1.1.1
#  flame_tiled: ^1.4.0
#  flame_audio: ^1.0.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  win32_gamepad: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/images/
    - assets/audio/music/bg_music.ogg
    - assets/audio/sfx/fire_1.mp3
    - assets/audio/sfx/fire_2.mp3
