name: practice_flame
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flame:
    path: packages/flame/packages/flame
  flame_tiled:
    path: packages/flame/packages/flame_tiled
  flame_audio:
    path: packages/flame/packages/flame_audio
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/tiles/map.tmx
    - assets/images/map-level1.png
    - assets/images/map-level2.png
    - assets/images/sprite-sheet-humn.png
    - assets/images/sprite-sheet-humn.json
    - assets/images/coins.png
    - assets/audio/music/bg_music.ogg
    - assets/audio/sfx/fire_1.mp3
    - assets/audio/sfx/fire_2.mp3
